
class Column_type:
    CASE_ID = 'CASE_ID'
    TRANSITION = 'TRANSITION'

    TEXT = 'TEXT'
    NUMBER = 'NUMBER'
    BOOLEAN = 'BOOLEAN'
    DATETIME = 'DATETIME'
    CATEGORICAL = 'CATEGORICAL'

    ACTIVITY = 'ACTIVITY'
    TIMESTAMP = 'TIMESTAMP'
    RESOURCE = 'RESOURCE'

    DURATION = 'DURATION'
    COST = 'COST'
    START_TIMESTAMP = 'START_TIMESTAMP'
    END_TIMESTAMP = 'END_TIMESTAMP'
