
class Status:
    WAITING = 'WAITING'
    PREPROCESSING = 'PREPROCESSING'
    TRAINING = 'TRAINING'
    TRAINED = 'TRAINED'
    ACTIVATING = 'ACTIVATING'
    STREAMING = 'STREAMING'
    SIMULATING = 'SIMULATING'
    ERROR = 'ERROR'
