name: Docker Image CI

on:
  push:
    tags:
      - '*'  # Trigger for all tags
  workflow_dispatch:
    inputs:
      manual_branch:
        description: Set branch
        required: true
        type: string
        default: test

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_NAMESPACE: ${{ secrets.DOCKER_NAMESPACE }}
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}

jobs:
  push_to_registry:
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref_type == 'tag' }}
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: api_meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPOSITORY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.api_meta.outputs.tags }}

